apiVersion: v1
kind: Pod
metadata: 
   name: curl-custom-sa-token
   namespace: rbac-test
   labels:
     week: "week11"
spec:
  serviceAccountName: mohammedk
  containers:
  - name: main
    image: curlimages/curl
    command: ["sleep", "999999"]
